### ISSUE TITLE
AttributeError: module 'traci' has no attribute 'Connection'

### ISSUE THREAD

**Issue by sallyqiansun** [robvoe/RELESAS#1]
Hello, thank you for providing the source code. When trying to run the code, I encountered the error as stated in the title, could I know how to proceed? Thanks in advance!

**Comment by robvoe** [comment]
Hi, thanks for reporting the issue. Did you install the conda environment as recommended in REDME.md? If not, please do so and try again. If the error persists, could you please also provide me with the full error output (stack trace)?

**Comment by robvoe** [comment]
Any news?
